content:
  - name: "Home Page"
    type: "document"
    path: "index.html"
    fields:
      - { name: "hero_name", label: "Full Name", type: "string" }
      - { name: "hero_subtitle", label: "Hero Subtitle", type: "rich-text" }
      - { name: "stat_years", label: "Years of Experience", type: "string" }
      - { name: "stat_community", label: "Community Stats", type: "string" }
      - { name: "stat_projects", label: "Partnership Stats", type: "string" }
      - { name: "kima_experience", label: "Kima Network Bullet Points", type: "rich-text" }
      - { name: "additional_experience", label: "Additional Experience", type: "rich-text" }
